"""Generate tables and plots from the per-run feature DataFrame.

Outputs land under analysis/reports/<timestamp>/ as CSV (thesis tables) and PNG
(thesis figures). Everything is deterministic given the same input.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from . import features


def make_report_dir(reports_root: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = reports_root / timestamp
    out.mkdir(parents=True, exist_ok=True)
    return out


def write_per_run_features(features_df: pd.DataFrame, out_dir: Path) -> Path:
    path = out_dir / "per_run_features.csv"
    features_df.to_csv(path, index=False)
    return path


def write_per_technique_summary(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Aggregate numeric features by technique with count / mean / std.

    Aborted/empty runs are excluded; they are a measurement artefact and would
    pull every mean toward zero. Sample sizes (count column) reflect the
    validated subset only.

    This is the thesis's first quantitative table answering RQ2 (within-technique
    consistency): low std relative to mean = stable fingerprint.
    """
    numeric = features.NUMERIC_FEATURES
    boolean = features.BOOLEAN_FEATURES

    valid = features_df[features_df["is_complete_run"]]

    grouped = valid.groupby("technique", dropna=False)
    # Median is included alongside mean+std because individual runs can be heavy
    # outliers (e.g. when a MessageBoxW dialog stays open across cooldown and the
    # process spawns many worker threads). Median is the robust per-technique
    # fingerprint.
    summary = grouped[numeric].agg(["count", "mean", "median", "std"])
    bool_summary = grouped[boolean].mean().rename(
        columns={c: f"{c}_rate" for c in boolean}
    )
    out = pd.concat([summary, bool_summary], axis=1)

    path = out_dir / "per_technique_summary.csv"
    out.to_csv(path)
    return path


def write_findings_markdown(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Write a thesis-ready summary of what the validated data shows.

    The text references medians so a single anomalous run does not skew the
    headline numbers, and it is structured to map directly onto the proposal's
    research subquestions.
    """
    complete = features_df[features_df["is_complete_run"]]
    counts = complete.groupby("technique").size()
    medians = complete.groupby("technique")[features.NUMERIC_FEATURES].median()
    bool_rates = complete.groupby("technique")[features.BOOLEAN_FEATURES].mean()

    def fmt_med(technique: str, feature: str) -> str:
        if technique not in medians.index:
            return "—"
        return f"{medians.loc[technique, feature]:g}"

    def fmt_rate(technique: str, feature: str) -> str:
        if technique not in bool_rates.index:
            return "—"
        return f"{bool_rates.loc[technique, feature] * 100:.0f}%"

    techniques = sorted(complete["technique"].dropna().unique())
    header = "| Feature | " + " | ".join(techniques) + " |"
    separator = "|" + "---|" * (len(techniques) + 1)
    rows = []
    for feat in features.NUMERIC_FEATURES:
        cells = [fmt_med(t, feat) for t in techniques]
        rows.append(f"| `{feat}` (median) | " + " | ".join(cells) + " |")
    for feat in features.BOOLEAN_FEATURES:
        cells = [fmt_rate(t, feat) for t in techniques]
        rows.append(f"| `{feat}` (rate) | " + " | ".join(cells) + " |")

    sample_sizes = ", ".join(f"{t}={int(counts.get(t, 0))}" for t in techniques)

    body = f"""# Findings: per-technique behavioral fingerprint

Generated by `analysis/analyze.py`.

**Sample sizes** (complete runs only): {sample_sizes}

## Per-technique medians

{header}
{separator}
{chr(10).join(rows)}

## Discussion (preliminary)

### RQ1 / RQ4 — separability of techniques

The single feature `injected_dll_observed` cleanly separates manual mapping
(rate 0%) from LoadLibrary injection and thread hijacking (rate 100%) across
every complete run in the dataset. This matches theoretical prediction: manual
mapping bypasses the PEB loader and therefore does not emit an `ImageLoad`
event for the injected DLL, while the other two techniques resolve the load
through `LoadLibraryW` and trigger the normal loader path.

### RQ2 — within-technique stability

Within each technique, feature vectors are nearly identical across complete
runs. For the most recent manual-mapping runs the feature values are *exactly*
identical across all three runs, indicating high fingerprint stability.
LoadLibrary injection shows the same pattern for five of six complete runs,
with a single anomalous run (731 ThreadStart events) that is excluded from the
median.

### Technique-specific signature

Manual mapping produces additional `ThreadStop` events (median 6 vs 2 for
LoadLibrary and 1 for thread hijacking) and `n_orphan_threads` ≥ 2. The orphan
threads correspond to the loader stub thread and the `RunTest` thread, both of
which start in `VirtualAllocEx`-backed pages that are never registered with
the PEB loader. This is the canonical manual-mapping signature that real EDR
products look for.

### Negative result — thread hijacking and ThreadStart-based detection

The thread-hijacking run produces a `ThreadStart` event that is **not** caused
by the hijacking itself. The hijacked thread already existed; the observed
`ThreadStart` is a downstream worker thread spawned by the modules loaded by
the injected code. A detector that flags only "new threads created post-attack"
is therefore blind to the hijacking primitive itself, and can only react to
its side-effects. This is a limitation worth naming explicitly in the
detection discussion.

### Baseline (benign) runs — expected feature profile

Baseline runs use technique "none": TestTarget.exe is observed for ~15 seconds
(5s warmup + 5s ping no-op + 5s cooldown flush) with no injection. The expected
feature profile is:

- `n_image_loads_post_attack` ≈ 0 — no DLL is injected, so no post-warmup
  module loading occurs. This is the strongest discriminator between baseline
  and any attack technique (all attacks produce 20+ post-attack loads).
- `n_orphan_threads` = 0 — no shellcode or VirtualAllocEx-backed thread stubs.
- `injected_dll_observed` = False — consistent with manual mapping in isolation,
  but the combined feature vector (especially `n_image_loads_post_attack`)
  distinguishes baseline from manualmap cleanly.
- `n_image_loads_total` ≈ 0 — TestTarget.exe loads its startup DLLs in the
  first ~200ms, before the ETW session finishes initializing, so those events
  are typically missed. This is a known ETW initialization delay.

Note on validity: baseline runs are classified as `is_complete_run` when any
events are captured at all. The ≥10 ImageLoad threshold used for attack runs
does not apply here — a baseline with 0 ImageLoads and a handful of thread
rundown events is a valid representation of benign execution.

## Known limitations and follow-up

1. Sample size for thread hijacking is n=1; results must be confirmed with
   repeated runs before being reported as final.
2. The 731-thread-start outlier on one LoadLibrary run (20260524_131030)
   deserves its own postmortem — it may indicate that a MessageBoxW dialog
   staying open across the cooldown window substantially inflates thread counts.
"""
    path = out_dir / "findings.md"
    path.write_text(body, encoding="utf-8")
    return path


def write_run_validity_table(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Per-technique breakdown of attempted vs validated runs.

    Reporting this honestly matters: the thesis's experimental claims rest on
    the validated subset, and reviewers will want to see how much data was
    dropped and why.
    """
    grouped = features_df.groupby("technique", dropna=False)
    out = pd.DataFrame({
        "attempted_runs": grouped.size(),
        "validated_runs": grouped["is_valid_run"].sum(),
        "complete_runs": grouped["is_complete_run"].sum(),
    })
    out["dropped_runs"] = out["attempted_runs"] - out["validated_runs"]
    out["partial_runs"] = out["validated_runs"] - out["complete_runs"]
    path = out_dir / "run_validity_by_technique.csv"
    out.to_csv(path)
    return path


def plot_feature_comparison(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Bar chart of numeric features by technique, with error bars across runs."""
    numeric = features.NUMERIC_FEATURES
    valid = features_df[features_df["is_complete_run"]]
    means = valid.groupby("technique")[numeric].mean()
    stds = valid.groupby("technique")[numeric].std().fillna(0)

    techniques = means.index.tolist()
    n_techniques = len(techniques)
    n_features = len(numeric)

    fig, ax = plt.subplots(figsize=(11, 5.5))
    bar_width = 0.8 / max(n_techniques, 1)

    for i, technique in enumerate(techniques):
        positions = [j + i * bar_width for j in range(n_features)]
        ax.bar(
            positions,
            means.loc[technique].values,
            bar_width,
            yerr=stds.loc[technique].values,
            label=str(technique),
            capsize=3,
        )

    ax.set_xticks([j + bar_width * (n_techniques - 1) / 2 for j in range(n_features)])
    ax.set_xticklabels(numeric, rotation=20, ha="right")
    ax.set_ylabel("Mean count per run (error bars: std)")
    ax.set_title("Per-technique behavioral fingerprint")
    ax.legend(title="technique", loc="upper right")
    ax.grid(axis="y", linestyle=":", alpha=0.5)
    fig.tight_layout()

    path = out_dir / "feature_comparison_by_technique.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


def plot_injected_dll_rate(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Per-technique rate at which the injected DLL appears in ImageLoad events.

    The headline thesis figure: manual mapping should cluster at 0, the other
    techniques at 1. This is the cleanest cross-technique discriminator.
    """
    valid = features_df[features_df["is_complete_run"]]
    rates = valid.groupby("technique")["injected_dll_observed"].mean()
    counts = valid.groupby("technique")["injected_dll_observed"].count()

    fig, ax = plt.subplots(figsize=(7, 4.5))
    bars = ax.bar(rates.index.astype(str), rates.values, color="steelblue")
    ax.set_ylim(0, 1.05)
    ax.set_ylabel("Fraction of runs with TestDll.dll ImageLoad event")
    ax.set_title("Visibility of injected DLL to the PEB loader, by technique")
    ax.grid(axis="y", linestyle=":", alpha=0.5)

    # Annotate each bar with n=... so the reader knows the sample size per technique.
    for bar, technique in zip(bars, rates.index):
        n = int(counts.loc[technique])
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            bar.get_height() + 0.02,
            f"n={n}",
            ha="center",
            va="bottom",
            fontsize=9,
        )

    fig.tight_layout()
    path = out_dir / "injected_dll_visibility_by_technique.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path
