"""CSV tables, markdown findings, and PNG figures generated from the feature
DataFrame. Outputs land under analysis/reports/<timestamp>/."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from . import features


# ---- Output directory ----

def make_report_dir(reports_root: Path) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out = reports_root / timestamp
    out.mkdir(parents=True, exist_ok=True)
    return out


# ---- CSV tables ----

def write_per_run_features(features_df: pd.DataFrame, out_dir: Path) -> Path:
    # Raw per-run dump: one row per run, every feature column. Reproducibility anchor.
    path = out_dir / "per_run_features.csv"
    features_df.to_csv(path, index=False)
    return path


def write_per_technique_summary(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Numeric features aggregated by (provider_set, technique). Median is the
    headline statistic — outlier runs (e.g. a stuck MessageBox spawning extra
    threads) skew the mean."""
    valid = features_df[features_df["is_complete_run"]]
    grouped = valid.groupby(["provider_set", "technique"], dropna=False)
    # Numeric features: count + mean + median + std per cell.
    summary = grouped[features.NUMERIC_FEATURES].agg(["count", "mean", "median", "std"])
    # Boolean features: cell mean = "fraction of runs where it fired" = rate.
    bool_summary = grouped[features.BOOLEAN_FEATURES].mean().rename(
        columns={c: f"{c}_rate" for c in features.BOOLEAN_FEATURES}
    )
    out = pd.concat([summary, bool_summary], axis=1)
    path = out_dir / "per_technique_summary.csv"
    out.to_csv(path)
    return path


def write_run_validity_table(features_df: pd.DataFrame, out_dir: Path) -> Path:
    # Honest sample-size reporting: attempted/validated/complete/dropped/partial per cell.
    grouped = features_df.groupby(["provider_set", "technique"], dropna=False)
    out = pd.DataFrame({
        "attempted_runs": grouped.size(),
        "validated_runs": grouped["is_valid_run"].sum(),
        "complete_runs": grouped["is_complete_run"].sum(),
    })
    out["dropped_runs"] = out["attempted_runs"] - out["validated_runs"]
    out["partial_runs"] = out["validated_runs"] - out["complete_runs"]
    path = out_dir / "run_validity_by_technique.csv"
    out.to_csv(path)
    return path


# ---- Markdown findings ----

def _format_feature_value(feature: str, value: float) -> str:
    # GrantedAccess is a bitmask — hex is the right format.
    if feature == "sysmon_max_granted_access":
        return f"0x{int(value):X}" if value > 0 else "0"
    return f"{value:g}"


def _medians_table_markdown(features_df: pd.DataFrame) -> str:
    """Markdown table: rows = numeric features, columns = (provider_set, technique).
    Each cell is the median of that feature across the cell's complete runs."""
    valid = features_df[features_df["is_complete_run"]]
    if valid.empty:
        return "_No complete runs available._"
    medians = valid.groupby(["provider_set", "technique"])[features.NUMERIC_FEATURES].median()
    pivot = medians.T
    cols = list(pivot.columns)
    header = "| Feature | " + " | ".join(f"{ps}<br>{t}" for ps, t in cols) + " |"
    sep = "|---|" + "---|" * len(cols)
    body_rows = []
    for feat in pivot.index:
        cells = [_format_feature_value(feat, pivot.loc[feat, c]) for c in cols]
        body_rows.append(f"| `{feat}` | " + " | ".join(cells) + " |")
    return "\n".join([header, sep, *body_rows])


def write_findings_markdown(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Short text companion to provider_visibility_matrix.png."""
    valid = features_df[features_df["is_complete_run"]]
    counts = valid.groupby(["provider_set", "technique"]).size()
    sample_sizes = "\n".join(
        f"- `{ps}` / `{t}` — n={int(n)}" for (ps, t), n in counts.items()
    ) or "- (no complete runs)"

    body = f"""# Findings

Generated by `python -m analysis.analyze`. Numbers reflect runs marked `is_complete_run`.
The headline figure is `provider_visibility_matrix.png` — this file is the
companion text. For per-run detail see `per_run_features.csv`; for stability
see `per_technique_summary.csv`; for sample-size honesty see
`run_validity_by_technique.csv`.

## Sample sizes

{sample_sizes}

## Numerical fingerprints (medians)

{_medians_table_markdown(features_df)}

## Reading the matrix

Under the kernel-process provider alone, injection techniques surface via the
DLL dependency cascade (`injected_dll_observed = 1` for loadlibrary and
threadhijack; `0` for manualmap because it bypasses the PEB loader). External
memory patching emits nothing — the empty column is the measurement.

Adding Sysmon surfaces the cross-process handle open (Event 10 ProcessAccess)
for every technique. The granted-access mask discriminates intent: a mask
intersecting `PROCESS_VM_WRITE | PROCESS_VM_OPERATION | PROCESS_CREATE_THREAD`
identifies the manipulation tool's handle and separates it from ambient noise
(background processes polling TestTarget for metadata request only
`PROCESS_QUERY_LIMITED_INFORMATION = 0x1000`). For memory patching this is
currently the only signal that distinguishes the technique from a benign run.
"""
    path = out_dir / "findings.md"
    path.write_text(body, encoding="utf-8")
    return path


# ---- PNG figures ----

def plot_provider_visibility_matrix(features_df: pd.DataFrame, out_dir: Path) -> Path:
    """Heatmap: rows = boolean detectors, columns = (provider_set, technique),
    cell = rate among complete runs."""
    boolean = features.BOOLEAN_FEATURES
    valid = features_df[features_df["is_complete_run"]]

    # Empty-data fallback so report generation never aborts on a fresh dataset.
    if valid.empty:
        fig, ax = plt.subplots(figsize=(7, 3))
        ax.text(0.5, 0.5, "No complete runs to display",
                ha="center", va="center", transform=ax.transAxes)
        ax.axis("off")
        path = out_dir / "provider_visibility_matrix.png"
        fig.savefig(path, dpi=150)
        plt.close(fig)
        return path

    # Detector rate per (provider_set, technique), transposed so detectors are rows.
    rates = valid.groupby(["provider_set", "technique"])[boolean].mean()
    pivot = rates.T

    # Figure size scales with shape so labels don't overlap.
    fig, ax = plt.subplots(figsize=(1.8 + 0.9 * pivot.shape[1], 0.55 * pivot.shape[0] + 1.5))
    im = ax.imshow(pivot.values, cmap="Blues", vmin=0.0, vmax=1.0, aspect="auto")

    # Axes: detectors on Y, (provider_set, technique) on X.
    ax.set_xticks(range(pivot.shape[1]))
    col_labels = [f"{ps}\n{t}" for (ps, t) in pivot.columns]
    ax.set_xticklabels(col_labels, rotation=30, ha="right", fontsize=8)
    ax.set_yticks(range(pivot.shape[0]))
    ax.set_yticklabels(pivot.index, fontsize=8)

    # Annotate each cell with its rate; text colour flips for contrast.
    for i in range(pivot.shape[0]):
        for j in range(pivot.shape[1]):
            v = pivot.values[i, j]
            ax.text(j, i, f"{v:.2f}",
                    ha="center", va="center",
                    color="white" if v >= 0.5 else "black",
                    fontsize=8)

    ax.set_title("Detector visibility per technique × provider set\n"
                 "(rate among complete runs)", fontsize=10)
    fig.colorbar(im, ax=ax, label="fraction of complete runs that fired the detector")
    fig.tight_layout()

    path = out_dir / "provider_visibility_matrix.png"
    fig.savefig(path, dpi=150)
    plt.close(fig)
    return path


